"""empty message

Revision ID: a411ea1ac745
Revises: d88ee7f93ab9
Create Date: 2025-05-19 00:38:17.382757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a411ea1ac745'
down_revision = 'd88ee7f93ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_member_class_name'), 'member', ['class_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_class_name'), table_name='member')
    # ### end Alembic commands ###
