"""Add class_name to Member

Revision ID: d88ee7f93ab9
Revises: e2acef9fc993
Create Date: 2025-05-19 00:10:33.974715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88ee7f93ab9'
down_revision = 'e2acef9fc993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('class_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'class_name')
    # ### end Alembic commands ###
