"""empty message

Revision ID: ea66efe361c2
Revises: a96fd36a550e
Create Date: 2025-04-15 23:48:56.698117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea66efe361c2'
down_revision = 'a96fd36a550e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_book_author'), 'book', ['author'], unique=False)
    op.create_index(op.f('ix_book_isbn'), 'book', ['isbn'], unique=False)
    op.create_index(op.f('ix_book_title'), 'book', ['title'], unique=False)
    op.alter_column('member', 'phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=9),
               existing_nullable=True)
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=False)
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.alter_column('member', 'phone',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_index(op.f('ix_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_isbn'), table_name='book')
    op.drop_index(op.f('ix_book_author'), table_name='book')
    op.drop_column('book', 'genre')
    # ### end Alembic commands ###?